force-app/main/default/objects/Card_Charge__c.object
<CustomObject>
    <description>This object contains a lookup to product and this object stores charge information of Products</description>
    <fields>
        <fullName>ATM_Fee_in_other_currencies__c</fullName>
        <description>The percentage of ATM Fee in other currencies</description>
        <inlineHelpText>Enter the ATM Fee for the product in the legal country!</inlineHelpText>
        <label>ATM Fee in other currencies</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <description>The Card Replacement Cost in different countries</description>
        <label>Card Replacement Cost</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_per_Calendar_Month__c</fullName>
        <description>This field contains the Cost per Calendar Month of Mastercards if applicable.</description>
        <inlineHelpText>Enter the Cost per Calendar Month for the product in the legal country!</inlineHelpText>
        <label>Cost per Calendar Month</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Country__c</fullName>
        <description>This picklist has all possible legal countries to select while storing product charges.</description>
        <label>Legal Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LegalCountryList</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup field for the product.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Card Charge</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Product Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <description>This field contains the country of the contact.</description>
        <label>Home Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LegalCountryList</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>The type of card products the customer own</description>
        <label>Product</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CardTypes</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/CardTypes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <description>This list contains the type of Mastercard or Visa</description>
    <masterLabel>CardTypes</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LegalCountryList.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
        <default>true</default>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
        <label>France</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>Spain</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <label>United Kingdom</label>
    </customValue>
    <description>List of legal countries, this is being used in Contact and Price Book Entry Objects</description>
    <masterLabel>LegalCountryList</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ui/CardInformationController.cls
/**
    * @description  This is a controller class to provide the card information to display in case layout
    * @author       revathyharidas@gmail.com
*/
public with sharing class CardInformationController {

	/**
    * @description  This is an apex wired method from the productInformation LWC to retrieve the card charge info
    * @param        caseId : current case record id			 
    */    
    @AuraEnabled(cacheable=true)
    public static List<Card_Charge__c> getCardChargeInfo(Id caseId){
       
        try {
          Contact currentCustomer = [SELECT Id, Product__c, Home_Country__c 
                                     FROM Contact Where Id IN (SELECT ContactId FROM CASE Where Id=: caseId) 
                                     WITH SECURITY_ENFORCED];
          List<String> productTypes = currentCustomer.Product__c.split(';');
          List<Card_Charge__c> cardChargesOfCustomer = [select id, Product__r.Name, Legal_Country__c, 
                                                              ATM_Fee_in_other_currencies__c, Card_Replacement_Cost__c, Cost_per_Calendar_Month__c 
                                                              FROM Card_Charge__c WHERE Product__r.Name IN: productTypes 
                                                              AND Legal_Country__c =:currentCustomer.Home_Country__c WITH SECURITY_ENFORCED];        
          return cardChargesOfCustomer; 
                        
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}