force-app/main/default/objects/Card_Charge__c.object
<CustomObject>
    <description>This object contains a lookup to product and this object stores charge information of Products</description>
    <fields>
        <fullName>ATM_Fee_in_other_currencies__c</fullName>
        <description>The percentage of ATM Fee in other currencies</description>
        <inlineHelpText>Enter the ATM Fee for the product in the legal country!</inlineHelpText>
        <label>ATM Fee in other currencies</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <description>The Card Replacement Cost in different countries</description>
        <label>Card Replacement Cost</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_per_Calendar_Month__c</fullName>
        <description>This field contains the Cost per Calendar Month of Mastercards if applicable.</description>
        <inlineHelpText>Enter the Cost per Calendar Month for the product in the legal country!</inlineHelpText>
        <label>Cost per Calendar Month</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Country__c</fullName>
        <description>This picklist has all possible legal countries to select while storing product charges.</description>
        <label>Legal Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LegalCountryList</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup field for the product.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Card Charge</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Product Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Charges</pluralLabel>
    <recordTypes>
        <fullName>Mastercard</fullName>
        <active>true</active>
        <description>This record type is specifically for credit/ debit mastercards</description>
        <label>Mastercard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>External_Contact_Id__C</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field will contain the unique identifier (UUID) from the external system that is mapped to every contact
record in Salesforce.</description>
        <externalId>true</externalId>
        <label>External Contact Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Home_Country__c</fullName>
        <description>This field contains the country of the contact.</description>
        <label>Home Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LegalCountryList</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>The type of card products the customer own</description>
        <label>Product</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CardTypes</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2.object
<CustomObject>
    <recordTypes>
        <fullName>MasterCard</fullName>
        <active>true</active>
        <description>This record type is specifically for Master debit and credit cards</description>
        <label>MasterCard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/CardTypes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <description>This list contains the type of Mastercard or Visa</description>
    <masterLabel>CardTypes</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LegalCountryList.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
        <default>true</default>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
        <label>France</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>Spain</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <label>United Kingdom</label>
    </customValue>
    <description>List of legal countries, this is being used in Contact and Price Book Entry Objects</description>
    <masterLabel>LegalCountryList</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/test/CardInfoTestFactory.cls
/**
* @description       : Test factory class for CardInformationController and N26DatatDispatcher
* @author            : revathyharidas@gmail.com
**/
public class CardInfoTestFactory {

    /*
   * description method to create a test user as custom support profile agent
   */
   public static void createCaseAgent() {
         User agentUser; 
           String agentEmail = 'agentTestUser@salesforce.com';
           String profileId = [SELECT Id FROM Profile WHERE Name ='Custom: Support Profile' LIMIT 1].Id;
           agentUser = new User(
               UserName = agentEmail,
               FirstName = 'Agent',
               LastName = 'Test User',
               Alias = string.valueOf(math.random()).substring(0,4),
               email = agentEmail,   
               ProfileID = profileId,
               TimeZoneSidKey = 'America/New_York',
               LocaleSidKey = 'en_US', 
               EmailEncodingKey = 'UTF-8', 
               LanguageLocaleKey = 'en_US'
           );
           Insert agentUser;
           
           PermissionSet appPermission = [SELECT Id FROM PermissionSet WHERE Name = 'N26CaseStudyApp'];
           
           INSERT new PermissionSetAssignment(
               AssigneeId = agentUser.Id,
               PermissionSetId = appPermission.Id
           );
   }
   
    /*
   * description creating multiple contacts, cases and card product and charge info for test
   */
   public static void createCaseCardTestData() {
        /*Inserting test contact record*/ 
           Contact contactRecord = new Contact(FirstName ='Test1', LastName='User1', Email = 'test1User@salesforce.com', 
                                               Home_Country__c='FR', Product__c ='Standard;Black',
                                               External_Contact_Id__c='a02529fc-788e-11ed-a1eb-0242ac120002'
                                              );
           Contact contactRecord1 = new Contact(FirstName ='Test2', LastName='User2', Email = 'test2User@salesforce.com', 
                                                Home_Country__c='DE', Product__c ='Metal',
                                                External_Contact_Id__c='a02529fc-788e-11ed-a1eb-0242bd120002'
                                               );
           List<Contact> contactsToInsert = new List<Contact>{contactRecord, contactRecord1};
               INSERT contactsToInsert;
           
           /*Inserting product records*/
           Product2 card1 = new Product2(Name='Standard', Family='MasterCard');
           Product2 card2 = new Product2(Name='Black', Family='MasterCard');
           Product2 card3 = new Product2(Name='Metal', Family='MasterCard');
           List<Product2> productsToInsert = new List<Product2>{card1,card2,card3};
               INSERT productsToInsert;
           
           /*Inserting case records*/
           Case caseRecord = new Case(Status = 'New', Origin = 'Email', Subject = 'Lost credit card', ContactId = contactsToInsert[0].id);
           Case caseRecord1 = new Case(Status = 'New', Origin = 'Phone',  Subject = 'Renew debit card' , ContactId = contactsToInsert[1].id);
           List<Case> casesToInsert = new List<Case>{caseRecord, caseRecord1};
               INSERT casesToInsert;
           
           /*Inserting card charge recs */
           List<Card_Charge__c> cardChargesToInsert = new List<Card_Charge__c>();
           for(Product2 productRec : [SELECT Id, Name FROM Product2 WHERE Name IN ('Standard', 'Black', 'Metal')]){
               Card_Charge__c card = new Card_Charge__c();
               card.Product__c = productRec.Id;
               card.Legal_Country__c = 'FR';
               card.ATM_Fee_in_other_currencies__c = 'Free';
               card.Card_Replacement_Cost__c = '€ 6';
               card.Cost_per_Calendar_Month__c = '€ 9,90';
               cardChargesToInsert.add(card);
               
               card = new Card_Charge__c();
               card.Product__c = productRec.Id;
               card.Legal_Country__c = 'DE';
               card.ATM_Fee_in_other_currencies__c = '1.7%';
               card.Card_Replacement_Cost__c = '€ 6';
               card.Cost_per_Calendar_Month__c = '€ 16,90';
               cardChargesToInsert.add(card);
           }
           
           INSERT cardChargesToInsert;
   }
   
}