force-app/main/default/objects/Card_Charge__c.object
<CustomObject>
    <description>This object contains a lookup to product and this object stores charge information of Products</description>
    <fields>
        <fullName>ATM_Fee_in_other_currencies__c</fullName>
        <description>The percentage of ATM Fee in other currencies</description>
        <inlineHelpText>Enter the ATM Fee for the product in the legal country!</inlineHelpText>
        <label>ATM Fee in other currencies</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <description>The Card Replacement Cost in different countries</description>
        <label>Card Replacement Cost</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_per_Calendar_Month__c</fullName>
        <description>This field contains the Cost per Calendar Month of Mastercards if applicable.</description>
        <inlineHelpText>Enter the Cost per Calendar Month for the product in the legal country!</inlineHelpText>
        <label>Cost per Calendar Month</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Country__c</fullName>
        <description>This picklist has all possible legal countries to select while storing product charges.</description>
        <label>Legal Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LegalCountryList</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup field for the product.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Card Charge</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Product Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>External_Contact_Id__C</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field will contain the unique identifier (UUID) from the external system that is mapped to every contact
record in Salesforce.</description>
        <externalId>true</externalId>
        <label>External Contact Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Home_Country__c</fullName>
        <description>This field contains the country of the contact.</description>
        <label>Home Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LegalCountryList</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>The type of card products the customer own</description>
        <label>Product</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CardTypes</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/CardTypes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <description>This list contains the type of Mastercard or Visa</description>
    <masterLabel>CardTypes</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LegalCountryList.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
        <default>true</default>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
        <label>France</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>Spain</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <label>United Kingdom</label>
    </customValue>
    <description>List of legal countries, this is being used in Contact and Price Book Entry Objects</description>
    <masterLabel>LegalCountryList</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/api/N26DataDisptacher.cls
/**
    * @description : This is a webservice to return the card-charge information associated with a contact
    * @author      : revathyharidas@gmail.com
*/
@RestResource(urlMapping='/v1/card-info/*')
global with sharing class N26DataDisptacher {
   
    /**
    * @description : GET method of the card Info associated with a particular customer
    * 				 This method will fetch the contact using the external id reference (UUID)
    * 				 and query the card charges according to the contact's card product type and country
    */
    @HttpGet
    global static void getCardInfoByContact() {
        final string UUID_REGEX = '^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$';      
        RestRequest request = RestContext.request;
        RestResponse response = RestContext.response;  
        String contactUUID =  RestContext.request.params.get('uuid');
        
        /*Input Validation for UUID*/
        Pattern uuidPattern = Pattern.compile(UUID_REGEX);
        Matcher uuidMatcher = uuidPattern.matcher(contactUUID);
        
        If(!uuidMatcher.matches()){            
            response.responseBody = Blob.valueOf('Invalid Input');
            response.statusCode = 400;
            return;
        }
               
        try{
            List<CardInfo> liInfo = new List<CardInfo>();
            Contact currentCustomer = [SELECT Id, Product__c, Home_Country__c FROM Contact Where External_Contact_Id__c=:contactUUID WITH SECURITY_ENFORCED];
            List<String> productTypes = currentCustomer.Product__c.split(';');
            for(Card_Charge__c cardCharge: [select id, Product__r.Name, Legal_Country__c, ATM_Fee_in_other_currencies__c, Card_Replacement_Cost__c,Cost_per_Calendar_Month__c FROM Card_Charge__c WHERE Product__r.Name IN: productTypes AND Legal_Country__c =:currentCustomer.Home_Country__c WITH SECURITY_ENFORCED]){
                CardInfo card = new CardInfo();
                card.card_type = cardCharge.Product__r.Name;
                card.country = cardCharge.Legal_Country__c;
                card.cost_per_calender_month = cardCharge.Cost_per_Calendar_Month__c;
                card.atm_fee_in_other_currencies = cardCharge.ATM_Fee_in_other_currencies__c;
                card.card_replacement_cost = cardCharge.Card_Replacement_Cost__c;
                liInfo.add(card);
            }
            response.responseBody = Blob.valueOf(JSON.serialize(liInfo));
            response.statusCode = 200;   
        }        
        catch(Exception ex){
            /*psuedo- code to Manage a custom object to store the logs for tracking errors in production 
            * EventLog__c eventLog = new EventLog__c('Error Message','error cause', 'Error component info', 'rest query param info', 'current user info')
            * insert asynchronously
            */
            System.debug(LoggingLevel.ERROR, 'Exception occured in N26DataDisptacher:getCardInfoByContact, Ex: '+ex.getMessage());
            response.responseBody = Blob.valueOf('Exception occured');
            response.statusCode = 500;
        }        
    }    

}