force-app/main/default/objects/Card_Charge__c.object
<CustomObject>
    <description>This object contains a lookup to product and this object stores charge information of Products</description>
    <fields>
        <fullName>ATM_Fee_in_other_currencies__c</fullName>
        <description>The percentage of ATM Fee in other currencies</description>
        <inlineHelpText>Enter the ATM Fee for the product in the legal country!</inlineHelpText>
        <label>ATM Fee in other currencies</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <description>The Card Replacement Cost in different countries</description>
        <label>Card Replacement Cost</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_per_Calendar_Month__c</fullName>
        <description>This field contains the Cost per Calendar Month of Mastercards if applicable.</description>
        <inlineHelpText>Enter the Cost per Calendar Month for the product in the legal country!</inlineHelpText>
        <label>Cost per Calendar Month</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Country__c</fullName>
        <description>This picklist has all possible legal countries to select while storing product charges.</description>
        <label>Legal Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LegalCountryList</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup field for the product.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Card Charge</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Product Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>External_Contact_Id__C</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field will contain the unique identifier (UUID) from the external system that is mapped to every contact
record in Salesforce.</description>
        <externalId>true</externalId>
        <label>External Contact Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Home_Country__c</fullName>
        <description>This field contains the country of the contact.</description>
        <label>Home Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LegalCountryList</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>The type of card products the customer own</description>
        <label>Product</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CardTypes</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/CardTypes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <description>This list contains the type of Mastercard or Visa</description>
    <masterLabel>CardTypes</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LegalCountryList.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
        <default>true</default>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
        <label>France</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>Spain</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <label>United Kingdom</label>
    </customValue>
    <description>List of legal countries, this is being used in Contact and Price Book Entry Objects</description>
    <masterLabel>LegalCountryList</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/test/CardInformationControllerTest.cls
/**
* @description       : Test class for CardInformationController
* @author            : revathyharidas@gmail.com
**/

@isTest
public class CardInformationControllerTest {
    
	/**
    *@description : Method to setup data for the test cases
    */
    @testSetup
    public Static void testDataSetup(){
        /*Inserting test contact record*/ 
        List<Contact> contactsToInsert = new List<Contact>();
        Contact contactRecord = new Contact(FirstName ='Test1', LastName='User', Email = 'test1User@salesforce.com', 
                                            Home_Country__c='FR', Product__c ='Standard;Black',
                                            External_Contact_Id__c='a02529fc-788e-11ed-a1eb-0242ac120002'
                                            );
        contactsToInsert.add(contactRecord);
        contactRecord = new Contact(FirstName ='Test2', LastName='User', Email = 'test2User@salesforce.com', 
                                            Home_Country__c='DE', Product__c ='Metal',
                                            External_Contact_Id__c='a02529fc-788e-11ed-a1eb-0242ac120002'
                                            );
        contactsToInsert.add(contactRecord);
        INSERT contactsToInsert;
       
        /*Inserting card product records*/
        Product2 card1 = new Product2(Name='Standard');
        Product2 card2 = new Product2(Name='Black');
        Product2 card3 = new Product2(Name='Metal');
        List<Product2> productsToInsert = new List<Product2>{card1,card2,card3};
        INSERT productsToInsert;
        
        /*Inserting case records*/
        Case caseRecord = new Case(Status = 'New', Origin = 'Email', Subject = 'Lost credit card', ContactId = contactsToInsert[0].id);
        Case caseRecord1 = new Case(Status = 'New', Origin = 'Phone',  Subject = 'Renew debit card' , ContactId = contactsToInsert[1].id);
        List<Case> casesToInsert = new List<Case>{caseRecord, caseRecord1};
        INSERT casesToInsert;
        
        /*Inserting card charge recs */
        List<Card_Charge__c> cardChargesToInsert = new List<Card_Charge__c>();
        for(Product2 productRec : [SELECT Id, Name FROM Product2 WHERE Name IN ('Standard', 'Black', 'Metal')]){
            Card_Charge__c card = new Card_Charge__c();
            card.Product__c = productRec.Id;
            card.Legal_Country__c = 'FR';
            card.ATM_Fee_in_other_currencies__c = 'Free';
            card.Card_Replacement_Cost__c = '€ 6';
            card.Cost_per_Calendar_Month__c = '€ 9,90';
            cardChargesToInsert.add(card);
            
            card = new Card_Charge__c();
            card.Product__c = productRec.Id;
            card.Legal_Country__c = 'DE';
            card.ATM_Fee_in_other_currencies__c = '1.7%';
            card.Card_Replacement_Cost__c = '€ 6';
            card.Cost_per_Calendar_Month__c = '€ 16,90';
            cardChargesToInsert.add(card);
        }
        
        INSERT cardChargesToInsert;
    }
    
    @isTest static void getCardChargeInfoTest() {
        
    }

}