force-app/main/default/objects/Card_Charge__c.object
<CustomObject>
    <description>This object contains a lookup to product and this object stores charge information of Products</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup field for the product.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Card Charge</label>
    <nameField>
        <displayFormat>PC-{0}</displayFormat>
        <label>Product Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Charges</pluralLabel>
    <recordTypes>
        <fullName>Mastercard</fullName>
        <active>true</active>
        <description>This record type is specifically for credit/ debit mastercards</description>
        <label>Mastercard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2.object
<CustomObject>
    <recordTypes>
        <fullName>MasterCard</fullName>
        <active>true</active>
        <description>This record type is specifically for Master debit and credit cards</description>
        <label>MasterCard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/test/Product2TriggerHandlerTest.cls
/**
* @description       : Test class for CardInformationController
* @author            : revathyharidas@gmail.com
**/

@isTest
public class Product2TriggerHandlerTest {
   /**
    *@description : Method to setup data for the test cases
    */
    @testSetup
    public Static void testDataSetup(){
        User adminUser = [select id, UserRoleId, Profile.name FROM User WHERE Profile.name ='System Administrator' Limit 1];
        System.runAs(adminUser){
           CardInfoTestFactory.createCaseCardTestData();
        }
    }
    
    /*
    * description delete product2 records
    */
    @isTest static void getCardChargeInfoTest_contact1() {
	  User adminUser = [select id, UserRoleId, Profile.name FROM User WHERE Profile.name ='System Administrator' Limit 1];        
        System.runAs(adminUser){
            List<Product2> cardProducts = [Select Id, Name FROM Product2 WHERE Family = 'MasterCard'];
            List<Card_Charge__c> cardCharges = [select id, Product__c  FROM Card_Charge__c WHERE Product__c IN: cardProducts];
            System.assertEquals(3, cardProducts.size());
            system.debug('cardCharges.size() '+cardCharges.size());
           // System.assertEquals(3, cardCharges.size());
            try{
                DELETE cardProducts;
                cardProducts = [Select Id, Name FROM Product2 WHERE Family = 'MasterCard'];
                cardCharges = [select id, Product__c  FROM Card_Charge__c WHERE Product__c IN: cardProducts];
          
            }
            catch(Exception ex){
                System.debug('Exception '+ex);
            }
        
        }
    }
}